### ISSUE TITLE
Question about equations 3 and 5 from paper

### ISSUE THREAD

**Issue by huard** [david0811/lafferty-sriver_inprep_tbd#1]
Hi, 

I have the impression that equations (3) and (5) from the papers don't match what is done in the code. The factors N_s, N_d and N_m in the denominator should not be there, since they're implicitly included for in the normalized weights. 

In 1D, if you have `m=[1,2,3]`, then `w = [1/6, 2/6, 3/6]` and to compute the weighted mean of `x`, you'd just do `sum(w * x)`, and not `sum(w * x)/3`. 

Could you confirm that I'm not mistaken, as I'm working on an implementation of your approach ?

Also, I'm looking for data that I could include in a unit test to confirm our implementation is sound and matches what is done in the paper. In other words, I want to do something like:
```
da = load_test_dataset()
expected = load_expected()
result = lafferty_sriver(da)
xarray.testing.assert_allclose(result, expected)
```
What would you suggest ?

Many thanks, 

David

**Comment by david0811** [comment]
Hi @huard

> Could you confirm that I'm not mistaken, as I'm working on an implementation of your approach ?

I believe you are correct! Thanks for digging in and finding this and letting me know. We will need to check if this merits an author correction... the results in the paper are fine given that the error is only in the manuscript text and not the code.

> Also, I'm looking for data that I could include in a unit test to confirm our implementation is sound and matches what is done in the paper.

I added a `unit_test` folder in this repo which hopefully satisfies your needs. Since the data underpinning the paper is too large to share over GitHub, I just uploaded a single csv file for one location. The notebook steps through applying our method to this data and confirms that it matches the results from the paper. I think this should be enough for your unit test but please let me know if you have additional questions or concerns.

**Comment by huard** [comment]
Don't fret too much about it. The paper is clear that a weighted average is being done, and I just realized the glitch in the equation when I checked that my implementation with `xarray.DataArray.weighted` matched the formula. 

This is really cool, thanks for taking the time!

Cheers, 

David
